# Generated by Django 4.2.25 on 2025-10-12 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Изображение сертификата')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL slug')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('tags', models.CharField(blank=True, help_text='Через запятую', max_length=500, verbose_name='Теги')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Фото профиля')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('education', models.TextField(verbose_name='Образование')),
                ('academic_degree', models.CharField(blank=True, max_length=255, verbose_name='Ученая степень')),
                ('academic_title', models.CharField(blank=True, max_length=255, verbose_name='Ученое звание')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('specialization', models.TextField(verbose_name='Специализация')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Лет опыта')),
                ('languages', models.CharField(help_text='Через запятую', max_length=255, verbose_name='Языки')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('researchgate', models.URLField(blank=True, verbose_name='ResearchGate')),
                ('orcid', models.CharField(blank=True, max_length=100, verbose_name='ORCID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('role', models.CharField(max_length=255, verbose_name='Роль в проекте')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация')),
                ('funding', models.CharField(blank=True, max_length=255, verbose_name='Финансирование')),
                ('results', models.TextField(blank=True, verbose_name='Результаты')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('publication_type', models.CharField(choices=[('article', 'Статья'), ('book', 'Книга'), ('chapter', 'Глава в книге'), ('conference', 'Конференция'), ('thesis', 'Диссертация')], default='article', max_length=20, verbose_name='Тип публикации')),
                ('authors', models.TextField(help_text='ФИО авторов через запятую', verbose_name='Авторы')),
                ('year', models.IntegerField(verbose_name='Год публикации')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Издатель')),
                ('journal', models.CharField(blank=True, max_length=255, verbose_name='Журнал')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Том')),
                ('pages', models.CharField(blank=True, max_length=50, verbose_name='Страницы')),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='DOI')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='ISBN')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('abstract', models.TextField(blank=True, verbose_name='Аннотация')),
                ('keywords', models.CharField(blank=True, help_text='Через запятую', max_length=500, verbose_name='Ключевые слова')),
                ('citation_count', models.IntegerField(default=0, verbose_name='Цитирования')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='PDF файл')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Избранная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена от')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Длительность')),
                ('icon', models.CharField(default='fas fa-chart-bar', max_length=100, verbose_name='CSS класс иконки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_position', models.CharField(max_length=255, verbose_name='Должность')),
                ('client_organization', models.CharField(max_length=255, verbose_name='Организация')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
                ('message', models.TextField(verbose_name='Описание запроса')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Предпочтительная дата')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ услуги',
                'verbose_name_plural': 'Заказы услуг',
                'ordering': ['-created_at'],
            },
        ),
    ]
