# Generated by Django 4.2.25 on 2025-10-12 08:50

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название книги')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL slug')),
                ('author', models.CharField(default='Ахмедова Ф.М.', max_length=500, verbose_name='Автор(ы)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('cover_image', models.ImageField(upload_to='books/covers/', verbose_name='Обложка')),
                ('pdf_file', models.FileField(help_text='PDF файл книги для просмотра', upload_to='books/pdfs/', verbose_name='PDF файл')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Издательство')),
                ('publication_year', models.IntegerField(verbose_name='Год издания')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='ISBN')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('language', models.CharField(default='Русский', max_length=50, verbose_name='Язык')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена в рублях', max_digits=10, null=True, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для заказа')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать на главной странице', verbose_name='Избранная')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-is_featured', 'order', '-publication_year'],
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание'),
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('message', models.TextField(blank=True, verbose_name='Дополнительные пожелания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Заказ книги',
                'verbose_name_plural': 'Заказы книг',
                'ordering': ['-created_at'],
            },
        ),
    ]
