# Generated by Django 4.2.25 on 2025-10-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_alter_blogpost_content_bookorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(blank=True, default='', help_text='Укажите цену (например, "10000") или "Договорная"', max_length=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.CharField(blank=True, help_text='Укажите цену (например, "10000") или "Договорная"', max_length=100, verbose_name='Цена от'),
        ),
    ]
